apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "kubernetes-backstage"
  annotations:
    backstage.io/kubernetes-id: value
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
