apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "kubernetes-backstage"
annotations:
  'backstage.io/kubernetes-namespace': default
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
