apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-web-app
  labels:
    backstage.io/kubernetes-id: node-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-web-app
  template:
    metadata:
      labels:
        app: node-web-app
        backstage.io/kubernetes-id: node-web-app
    spec:
      containers:
        - name: node-web-app
          image: localhost:32000/node-web-app:latest
          
